// Generated by Wrangler on Mon Jul 08 2024 13:19:31 GMT+0400 (Gulf Standard Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	WARPCAST_BASE_URL: "https://client.warpcast.com";
	LILNOUNS_SUBGRAPH_URL: "https://api.goldsky.com/api/public/project_cldjvjgtylso13swq3dre13sf/subgraphs/lil-nouns-subgraph/1.0.4/gn";
	WARPCAST_ACCESS_TOKEN: string;
}
