/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: b0cf46816c5dfa41ff9b8fbb82cb0453)
declare namespace Cloudflare {
	interface Env {
		KV: KVNamespace;
		WARPCAST_BASE_URL: string;
		LILNOUNS_SUBGRAPH_URL: string;
		LOG_LEVEL: string;
		WARPCAST_ACCESS_TOKEN: string;
		WARPCAST_API_KEY: string;
		ALCHEMY_API_KEY: string;
		ANKR_API_KEY: string;
		DB: D1Database;
		QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
