/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 4f46059d7c1695d7c2d122461913dbe6)
declare namespace Cloudflare {
	interface Env {
		KV: KVNamespace;
		WARPCAST_BASE_URL: string;
		LILNOUNS_SUBGRAPH_URL: string;
		LOG_LEVEL: string;
		WARPCAST_ACCESS_TOKEN: string;
		WARPCAST_API_KEY: string;
		ALCHEMY_API_KEY: string;
		ANKR_API_KEY: string;
		QUEUE: Queue;
	}
}
interface Env extends Cloudflare.Env {}
